Repository CS2113-AY1819S1-T12-2/main, pull requests merged in 2018-11, with the labels that each got.

#141 Fixed `BloodType`, `Height`, and `Weight` classes
  src/main/java/seedu/address/model/person/addinfo/BloodType.java
  src/main/java/seedu/address/model/person/addinfo/Height.java
  src/main/java/seedu/address/model/person/addinfo/Weight.java
Labels: severity.high, type.bug, v1.4

#142 fixed bugs for BloodType, PrevCountry and Allergy
  src/main/java/seedu/address/model/person/AllergyContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/BloodTypeContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/CountryContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/model/person/AddressContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/AllergyContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/BloodTypeContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/CountryContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/InfoContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NricContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/TagContainsKeywordsPredicateTest.java
Labels: priority.high

#144 Enhancements for v1.4
  src/main/java/seedu/address/logic/commands/AddMedicalReportCommand.java
  src/main/java/seedu/address/logic/commands/EditMedicalReportCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditMedicalReportCommandParser.java
  src/main/java/seedu/address/ui/InfoPanel.java
  src/main/java/seedu/address/ui/ReportCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InfoPanel.fxml
  src/main/resources/view/ReportCard.fxml
Labels: priority.high, type.enhancement, v1.4

#136 Adding error messages, creating edithist command and writing test codes.
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/commands/AddHistCommand.java
  src/main/java/seedu/address/logic/commands/EditHistCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditHistCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/medhistory/Allergy.java
  src/main/java/seedu/address/model/medhistory/MedHistory.java
  src/main/java/seedu/address/model/medhistory/MedHistoryComparator.java
  src/main/java/seedu/address/ui/InfoPanel.java
  src/main/java/seedu/address/ui/MedHistoryCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/hospital-sign.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InfoPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MedHistoryCard.fxml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: priority.high, status.ongoing, type.enhancement, v1.4

#189 Changes to info panel and sample data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/InfoPanel.java
Labels: priority.medium, v1.4

#146 Addressed issue #65, #117, #125, #178, #190
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/exceptions/EncryptionException.java
  src/main/java/seedu/address/commons/util/SecretKeyUtil.java
  src/main/java/seedu/address/commons/util/XmlUtil.java
  src/main/java/seedu/address/logic/commands/AddApptCommand.java
  src/main/java/seedu/address/logic/commands/AddHistCommand.java
  src/main/java/seedu/address/logic/commands/AddInfoCommand.java
  src/main/java/seedu/address/logic/commands/AddMedicalReportCommand.java
  src/main/java/seedu/address/logic/commands/DeleteApptCommand.java
  src/main/java/seedu/address/logic/commands/EditApptCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditHistCommand.java
  src/main/java/seedu/address/logic/commands/EditMedicalReportCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddInfoCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/addinfo/DateOfBirth.java
  src/main/java/seedu/address/model/person/addinfo/MaritalStatus.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/InfoPanel.java
  src/main/resources/view/InfoPanel.fxml
  src/test/data/XmlSerializableAddressBookTest/duplicatePersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
Labels: priority.high, type.enhancement, v1.4

#197 v1.4 Final checks and tests
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/AddApptUGPic.png
  docs/images/AddApptUGPic2.png
  docs/images/AddReport.png
  docs/images/EditReport.png
  docs/images/FindActivityDiagram.png
  docs/images/SortActivityDiagram.png
  docs/images/addhist.png
  docs/images/edithist.png
  docs/team/brandonccm1996.adoc
  docs/team/chewkahmeng.adoc
  docs/team/chokxy.adoc
  docs/team/xshaivan.adoc
  src/main/java/seedu/address/logic/commands/AddHistCommand.java
  src/main/java/seedu/address/logic/commands/EditHistCommand.java
  src/main/java/seedu/address/logic/parser/EditHistCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/medhistory/Allergy.java
  src/main/java/seedu/address/model/medhistory/PrevCountry.java
  src/main/java/seedu/address/model/util/DateTimeUtil.java
  src/test/java/seedu/address/logic/commands/AddHistCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/EditHistCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/AddHistTest.java
  src/test/java/seedu/address/testutil/EditHistDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalMedHistory.java
Labels: priority.high, type.task, v1.4

#217 fixed issue #165 and issue #149
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
Labels: priority.high

#225 Final v1.4 documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/medhistoryV2.png
Labels: priority.high, type.task, v1.4

#227 Adding underscores to test cases.
  src/test/java/seedu/address/logic/commands/AddHistCommandTest.java
  src/test/java/seedu/address/logic/commands/AddReportCommandTest.java
  src/test/java/seedu/address/logic/parser/AddHistCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddReportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditHistCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditReportCommandParserTest.java
  src/test/java/seedu/address/model/medicalreport/InformationTest.java
  src/test/java/seedu/address/model/medicalreport/MedicalReportTest.java
  src/test/java/seedu/address/model/medicalreport/ReportDateTest.java
  src/test/java/seedu/address/model/medicalreport/TitleTest.java
Labels: priority.low, type.task, v1.4

#231 Added tests to medhistory model
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/AddHistSequenceDiagram.png
  docs/team/xshaivan.adoc
  src/main/java/seedu/address/model/medhistory/MedHistDate.java
  src/test/java/seedu/address/model/medhistory/AllergyTest.java
  src/test/java/seedu/address/model/medhistory/MedHistDateTest.java
  src/test/java/seedu/address/model/medhistory/PrevCountryTest.java
Labels: priority.low, type.task, v1.4
