Repository CS2113-AY1819S1-T12-2/main, pull requests merged in 2018-10, with the labels that each got.

#29 Implementation of addinfo NRIC Command
  README.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddApptCommand.java
  src/main/java/seedu/address/logic/commands/AddHistCommand.java
  src/main/java/seedu/address/logic/commands/AddInfoCommand.java
  src/main/java/seedu/address/logic/commands/AddMedicalReportCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditInfoCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddInfoCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/duplicatePersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/logic/commands/AddInfoCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddInfoCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/NricTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: v1.1

#45 Timetable end v1.2
  src/main/java/seedu/address/logic/commands/AddApptCommand.java
  src/main/java/seedu/address/logic/commands/AddHistCommand.java
  src/main/java/seedu/address/logic/commands/AddInfoCommand.java
  src/main/java/seedu/address/logic/commands/AddMedicalReportCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedAppt.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/AddApptCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalAppts.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: v1.2

#47 Made addreport command able to add a list of reports
  src/main/java/seedu/address/logic/commands/AddApptCommand.java
  src/main/java/seedu/address/logic/commands/AddHistCommand.java
  src/main/java/seedu/address/logic/commands/AddInfoCommand.java
  src/main/java/seedu/address/logic/commands/AddMedicalReportCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddMedicalReportCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/medhistory/MedHistDate.java
  src/main/java/seedu/address/model/medicalreport/MedicalReport.java
  src/main/java/seedu/address/model/medicalreport/ReportDate.java
  src/main/java/seedu/address/model/person/DateOfBirth.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/timetable/ApptDateTime.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/storage/XmlAdaptedReport.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/AddReportCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddReportCommandParserTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/ReportBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalReports.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: v1.2

#68 Updated User Guide and Developer Guide for addinfo
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.low, type.task, v1.2

#50 V1.2 Changing MedHistory to use Set
  src/main/java/seedu/address/logic/commands/AddHistCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedMedHistory.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/AddHistCommandTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: v1.2

#52 Multiple Arguments for Additional Info and Date of Birth Implementation
  docs/UserGuide.adoc
  docs/UsingGradle.adoc
  src/main/java/seedu/address/logic/commands/AddApptCommand.java
  src/main/java/seedu/address/logic/commands/AddHistCommand.java
  src/main/java/seedu/address/logic/commands/AddInfoCommand.java
  src/main/java/seedu/address/logic/commands/AddMedicalReportCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddInfoCommandParser.java
  src/main/java/seedu/address/logic/parser/AddMedicalReportCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/medicalreport/MedicalReport.java
  src/main/java/seedu/address/model/person/DateOfBirth.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/storage/XmlAdaptedReport.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlAddressBookStorageTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/duplicatePersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/java/seedu/address/logic/commands/AddInfoCommandTest.java
  src/test/java/seedu/address/logic/commands/AddInfoPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddInfoCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/DateOfBirthTest.java
  src/test/java/seedu/address/testutil/AddInfoPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/ReportBuilder.java
  src/test/java/seedu/address/testutil/ReportUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
Labels: priority.high, type.task, v1.2

#58 Find by keyword with Prefix V1.2
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/AddressContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/person/AddressContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/tag/TagContainsKeywordsPredicateTest.java
Labels: v1.2

#79 Updated JUnit Test
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/AddInfoCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: priority.medium, type.task, v1.2

#89 update documentation for find and sort
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.high, type.task, v1.3

#88 Timetable v1.3 ui
  src/main/java/seedu/address/logic/commands/AddApptCommand.java
  src/main/java/seedu/address/logic/parser/AddApptCommandParser.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/timetable/Appt.java
  src/main/java/seedu/address/model/timetable/ApptComparator.java
  src/main/java/seedu/address/model/timetable/ApptDateTime.java
  src/main/java/seedu/address/model/timetable/ApptDrName.java
  src/main/java/seedu/address/model/timetable/ApptInfo.java
  src/main/java/seedu/address/model/timetable/ApptVenue.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedAppt.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/InfoPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/BrowserPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InfoPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/guitests/guihandles/InfoPanelHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/WebViewUtil.java
  src/test/java/seedu/address/logic/commands/AddApptCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddApptCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/timetable/ApptTest.java
  src/test/java/seedu/address/testutil/ApptBuilder.java
  src/test/java/seedu/address/testutil/ApptUtil.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalAppts.java
  src/test/java/seedu/address/ui/InfoPanelTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: v1.3

#82 v1.3 Enhancement: Allow prefixes to be optional
  src/main/java/seedu/address/logic/commands/AddHistCommand.java
  src/main/java/seedu/address/logic/parser/AddHistCommandParser.java
  src/main/java/seedu/address/model/medhistory/MedHistory.java
  src/main/java/seedu/address/storage/XmlAdaptedMedHistory.java
  src/test/java/seedu/address/testutil/MedHistoryBuilder.java
  src/test/java/seedu/address/testutil/MedHistoryUtil.java
Labels: priority.high, status.ongoing, type.task, v1.3

#86 Enhancements for Medical Report v1.3
  src/main/java/seedu/address/logic/commands/AddMedicalReportCommand.java
  src/main/java/seedu/address/logic/parser/AddMedicalReportCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/medicalreport/Information.java
  src/main/java/seedu/address/model/medicalreport/MedicalReport.java
  src/main/java/seedu/address/model/medicalreport/ReportDate.java
  src/main/java/seedu/address/model/medicalreport/Title.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/XmlAdaptedReport.java
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/logic/commands/AddReportCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddReportCommandParserTest.java
  src/test/java/seedu/address/model/person/AddMedicalReportTest.java
  src/test/java/seedu/address/testutil/ReportBuilder.java
  src/test/java/seedu/address/testutil/ReportUtil.java
  src/test/java/seedu/address/testutil/TypicalReports.java
Labels: v1.3

#84 Implemented Height and Weight Attributes, NRIC Checksum Algorithm
  src/main/java/seedu/address/logic/commands/AddApptCommand.java
  src/main/java/seedu/address/logic/commands/AddHistCommand.java
  src/main/java/seedu/address/logic/commands/AddInfoCommand.java
  src/main/java/seedu/address/logic/commands/AddMedicalReportCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddInfoCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/addinfo/BloodType.java
  src/main/java/seedu/address/model/person/addinfo/DateOfBirth.java
  src/main/java/seedu/address/model/person/addinfo/Gender.java
  src/main/java/seedu/address/model/person/addinfo/Height.java
  src/main/java/seedu/address/model/person/addinfo/Nric.java
  src/main/java/seedu/address/model/person/addinfo/Weight.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlSerializableAddressBookTest/duplicatePersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/DateOfBirthTest.java
  src/test/java/seedu/address/model/person/NricTest.java
  src/test/java/seedu/address/testutil/AddInfoPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
Labels: priority.high, status.ongoing, type.task, v1.3

#90 Added new predicates - Allergy, BloodType, Country, MedInfo, Nric
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/AllergyContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/BloodTypeContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/CountryContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/InfoContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NricContainsKeywordsPredicate.java
Labels: priority.high, type.enhancement, type.task, v1.3

#112 Updated UGDG and PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/xhxh96.adoc
Labels: type.task, v1.3

#114 Update UGDG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: v1.3

#100 Timetable v1.3
  src/main/java/seedu/address/logic/commands/AddApptCommand.java
  src/main/java/seedu/address/logic/commands/DeleteApptCommand.java
  src/main/java/seedu/address/logic/commands/EditApptCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddApptCommandParser.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddMedicalReportCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteApptCommandParser.java
  src/main/java/seedu/address/logic/parser/EditApptCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/ui/ApptCard.java
  src/main/java/seedu/address/ui/InfoPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/ApptCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InfoPanel.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/logic/commands/DeleteApptCommandTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: priority.high, type.epic, v1.3

#97 Enhancements for v1.3
  src/main/java/seedu/address/logic/commands/AddMedicalReportCommand.java
  src/main/java/seedu/address/logic/commands/EditMedicalReportCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddMedicalReportCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditMedicalReportCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/medicalreport/Information.java
  src/main/java/seedu/address/model/medicalreport/ReportComparator.java
  src/main/java/seedu/address/model/medicalreport/Title.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/test/java/seedu/address/logic/parser/AddReportCommandParserTest.java
  src/test/java/seedu/address/testutil/ReportUtil.java
Labels: priority.high, type.epic, v1.3

#103 Added DischargeStatus in UGDG and added Project Portfolio
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/hovantan.adoc
Labels: priority.low, type.task, v1.3

#109 Find by newly added patient details with multiple keywords
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/AddressContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/AllergyContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/BloodTypeContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/CountryContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/InfoContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NricContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/addinfo/BloodType.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.high, type.enhancement, v1.3
